### ISSUE TITLE
Only collapse nested quotes

### ISSUE THREAD

**Issue by null-git** [mjg/QuoteCollapse#11]
It would be nice if there was an option to only collapse n-th level quotes and those below.

I'm reading a few mailing lists where people use the interleaved reply style extensively. It would be nice to have the first level of quotation uncollapsed, so that you know what the reply is about, and everything below that collapsed to save you a lot of scrolling.

**Comment by stanio** [comment]
Have you tried the _"Always keep 1st level expanded"_ [customization](http://mjg.github.io/QuoteCollapse/customising.html#style)?

Apart from this I would advertise to try the _"Partially collapse quotes"_ customization (the last one on the same page), instead.  Always having full quote expanded may still be annoying with excessive quotes.  You could tweak the amount of initially revealed lines to your liking.

**Comment by null-git** [comment]
Damn. I didn't tried the homepage first.
This works great. Thank you and sorry for wasting your time.
