### ISSUE TITLE
Fix for issue #7 fdoesn't work with Thunderbird 60.4

### ISSUE THREAD

**Issue by blu28** [mjg/QuoteCollapse#12]
After upgrading Thunderbird to version 60.4, I am now seeing overlapping text, probably the same issue as issue #7. The fix in that issue says to modify the userContent.css file, especially if you had a customized one. However, I cannot find a userContent.css file anywhere in any directory related to Thunderbird, not in my profile directory, not in the Program files directory. 

Oddly, I am only having the problem on a Windows 7 system that has had Thunderbird installed and upgraded over the years, but not running the same version of Thunderbird on a Windows 10 system that is less than a year old.

**Comment by stanio** [comment]
> Oddly, I am only having the problem on a Windows 7 system that has had Thunderbird installed and upgraded over the years...

Please double check you don't have old customization applied, and if necessary adjust as [documented](http://mjg.github.io/QuoteCollapse/customising.html):

> _Note,_ up to QuoteCollapse v0.9 the default styles used CSS `height` property instead of `max-height`. If you upgrade from that version you'll need to adjust old customizations like: `height: auto` → `max-height: none`, and replace other `height` usages for `max-height`.

**Comment by stanio** [comment]
> Please double check you don't have old customization applied...

To verify try creating a fresh [new profile](https://support.mozilla.org/en-US/kb/using-multiple-profiles#w_starting-the-profile-manager).

**Comment by blu28** [comment]
I don't seem to have any usercontent.css file. Are there other files that the customization might be in?

**Comment by stanio** [comment]
Not sure you could still have this with Thunderbird, but do you have extension like [Stylish](https://addons.mozilla.org/addon/stylish/) or [Stylus](https://addons.mozilla.org/addon/styl-us/) installed? Then try a new profile with only QuoteCollapse installed and see if problem gets reproduced.

**Comment by mjg** [comment]
Please retry with TB 91 and the QCC Add On, see issue #14 and the link in the new README.
