### ISSUE TITLE
Message display mangled in Thunderbird 52.7.0

### ISSUE THREAD

**Issue by marcnarc** [mjg/QuoteCollapse#2]
Upgraded to Thunderbird 52.7.0 today (Kubuntu 17.10, 64-bit), and Quote Collapse is mangling messages.

For example:
![thunderbird-quotecollapse-mangle](https://user-images.githubusercontent.com/14980203/38256027-550ebbee-372b-11e8-8b56-c5668b03f968.png)

The message is a simple text/plain with a single layer of quoting:

```
To: Mark Nottingham <mnot@mnot.net>, HTTP Working Group <ietf-http-wg@w3.org>
Cc: Patrick McManus <mcmanus@ducksong.com>
References: <CC507CB4-72AB-41F8-BEAB-66EB3B4152C9@mnot.net>
From: =?UTF-8?Q?Lo=c3=afc_Hoguin?= <essen@ninenines.eu>
Organization: Nine Nines
Message-ID: <a05bf0d9-9426-84c0-09b2-9f9ed8e0dadc@ninenines.eu>
Date: Tue, 3 Apr 2018 16:17:34 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101
 Thunderbird/52.7.0
MIME-Version: 1.0
In-Reply-To: <CC507CB4-72AB-41F8-BEAB-66EB3B4152C9@mnot.net>
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Language: en-US
Content-Transfer-Encoding: 8bit
Subject: Re: Working Group Last Call: Bootstrapping WebSockets with HTTP/2
Archived-At: <https://www.w3.org/mid/a05bf0d9-9426-84c0-09b2-9f9ed8e0dadc@ninenines.eu>
Resent-From: ietf-http-wg@w3.org
X-Mailing-List: <ietf-http-wg@w3.org> archive/latest/35227
X-Loop: ietf-http-wg@w3.org
Resent-Sender: ietf-http-wg-request@w3.org
Precedence: list
List-Id: <ietf-http-wg.w3.org>
List-Help: <https://www.w3.org/Mail/>
List-Post: <mailto:ietf-http-wg@w3.org>
List-Unsubscribe: <mailto:ietf-http-wg-request@w3.org?subject=unsubscribe>

On 03/28/2018 11:48 PM, Mark Nottingham wrote:
> Hi everyone,
> 
> Patrick (as editor) has incorporated the discussion from London and believes this is ready for WGLC; there are no open issues.
> 
> Please have a look at:
>    https://tools.ietf.org/html/draft-ietf-httpbis-h2-websockets-01
> 
> ... and bring up any issues on-list or on its issues list; likewise statements of support (or otherwise) for publication on-list would be appreciated.

Hello,

I am finalizing a server implementation. Just tried it against Chrome 
and things work as intended, with and without permessage-deflate.

I was a little surprised to see that the value for 
SETTINGS_ENABLE_CONNECT_PROTOCOL (0x8) is only defined in the IANA 
considerations.

I would +1 the need for some language on the END_STREAM flag, including 
how endpoints should behave when END_STREAM (or RST_STREAM) is sent on 
the stream without a close frame. I assume it's the same behavior as if 
an HTTP/1.1 Websocket connection was improperly closed but it would be 
nice to have confirmation.

Thanks for the great spec!

Cheers,

-- 
LoÃ¯c Hoguin
https://ninenines.eu
```

**Comment by bertwesarg** [comment]
Same problem here. Do you have the 'Always keep 1st level expanded' customizations in your `userContent.css` active? Removing this works, but I would like to have this feature back.

**Comment by marcnarc** [comment]
Yes, I do have "Always keep 1st level expanded".

Looking at the CSS, it seems that I'm using an outdated version (I've been using QuoteCollapse for years).  In my CSS all three rules set the **height** property, but it seems that this should be **max-height**.  Making that change in my CSS fixes the problem, at least for me.

**Comment by stanio** [comment]
Yes, the new version uses CSS `max-height` vs. `height` to support _partially collapsed quotes_ use case (#1).  This has been noted in few places – the [release notes](https://addons.mozilla.org/addon/quotecollapse/versions/1.0):

> * [Backward-compatibility] Default styles now use max-height instead of height. Existing customizations need to be adjusted – see Customising on the website for details;

The CSS code on the [_Customising_](http://mjg.github.io/QuoteCollapse/customising.html) page has been adjusted appropriately, and a [note](http://mjg.github.io/QuoteCollapse/customising.html#height-compat) added:

> _Note,_ up to QuoteCollapse v0.9 the default styles used CSS `height` property instead of `max-height`. If you upgrade from that version you'll need to adjust old customizations like: `height: auto` → `max-height: none`, and replace other `height` usages for `max-height`.

**Comment by marcnarc** [comment]
Thanks!

The note on the Customizing page reads (in part):

> adjust old customizations like: height: auto → max-height: none

Shouldn't it be "max-height: auto"?

**Comment by stanio** [comment]
> Shouldn't it be "max-height: auto"?

Nope. See:

-   https://developer.mozilla.org/docs/Web/CSS/max-height
-   https://www.w3.org/TR/CSS2/visudet.html#propdef-max-height

**Comment by stanio** [comment]
Apart from docs / release notes, I'm curious if this incompatibility change could be better advertised – any ideas?

**Comment by marcnarc** [comment]
**Re: max-height: none**

Right, my bad.  I thought I'd left it as "auto" in my CSS, but it is indeed "none."

**Comment by marcnarc** [comment]
> Apart from docs / release notes, I'm curious if this incompatibility change could be better advertised – any ideas?

No, unfortunately.

I have several extensions that open a tab when they update (or when T-bird first starts after the extension has updated).  I find these quite ignorable; they're easily closed without even looking at them.

For me, you might have better luck inserting an email in my inbox.  I have no idea how feasible that is for a plugin, though.

**Comment by svitalsky** [comment]
I have similar (the same? … I didn't really read the discussion here thoroughly) problem: quoted text bits being rendered over other text &c. I had to simplify the quotecollapse.js file (see the diff bellow) but I am afraid it might defy the purpose of the last changes in this extension (that I've been using for years). For me however this works perfectly.

(Also, I am not very proficient with JS; I hate it, really.)
```diff
65d64
<  max-height: 2.25ex;\n\
67d65
<  overflow: -moz-hidden-unscrollable;\n\
72,73d69
<  max-height: none;\n\
<  overflow: visible;\n\
78,79d73
<  max-height: 2.25ex;\n\
<  overflow: -moz-hidden-unscrollable;\n\
90,91c84,85
<       if(current.nodeName == "BLOCKQUOTE" && current.getAttribute("qctoggled") != "true")
<         return false;
---
>       if (current.nodeName == "BLOCKQUOTE")
>          return current.getAttribute("qctoggled") == "true";
```

**Comment by stanio** [comment]
> I have similar (the same? … I didn't really read the discussion here thoroughly) problem...

Please read my first [comment](#issuecomment-382641374) here and see if this resolves the problem for you.

**Comment by svitalsky** [comment]
@stanio I have no customization for this extension, so if I understand correctly what those release notes say it doesn't apply to my case.

**Comment by stanio** [comment]
@svitalsky, interesting – I had previously encountered this effect but it was just because I've mixed various user style customizations with different versions of the extension.  The patch you've applied looks a bit weird as you seems have removed almost all core styles the extension relies on – if the extension continues to work for you, I'm guessing you really have a customization (buried somewhere?) which pretty much redefines the necessary styles.  You may check what styles are applied, and their source using the Developer Tools, if you're familiar with them.

**Comment by svitalsky** [comment]
@stanio Turns out you are right, there was some old customization. I have no memory whatsoever about creating or downloading it, but it was there. After removing it the problem with mangled text was fixed, but when I replaced it with some customization from above linked page, another one appeared. It's different however so I'll just open a new issue. Thx.

**Comment by mjg** [comment]
Thanks for weeding this out.

I'm closing this (but am open for suggestions to advertise changes in a better way).

**Comment by stanio** [comment]
> I'm closing this (but am open for suggestions to advertise changes in a better way).

It's a minor thing but I remember AMO supporting some HTML in descriptions, so if possible hyper-link "Customizing" in the [version notes](https://addons.mozilla.org/addon/quotecollapse/versions/1.0):

> -   [Backward-compatibility] Default styles now use max-height instead of height. Existing customizations need to be adjusted – see [Customising](http://mjg.github.io/QuoteCollapse/customising.html#height-compat) on the website for details;

May be even add the referenced paragraph as part of the AMO description:

> **Version 0.9 → 1.0+ compatibility**
> 
> _Note,_ up to QuoteCollapse v0.9 the default styles used CSS `height` property instead of `max-height`. If you upgrade from that version you'll need to adjust any old customizations like: `height: auto` → `max-height: none`, and replace other `height` usages for `max-height`.

**Comment by stanio** [comment]
I've now sent message to the `mozilla.support.thunderbird` and `mozilla.support.seamonkey` [groups](https://www.mozilla.org/en-US/about/forums/#end-user-support) stressing the necessity of user adjustments after the upgrade:

* https://groups.google.com/d/msg/mozilla.support.thunderbird/3fE5npvvSQU/qeLAfB7LAAAJ
* https://groups.google.com/d/msg/mozilla.support.seamonkey/KEbgxNArDPc/_1UpBZCKCgAJ
