### ISSUE TITLE
Broken in Thunderbird 60

### ISSUE THREAD

**Issue by wsmwk** [mjg/QuoteCollapse#3]
Thunderbird 60 has enabled strict compaibility, meaning the addon needs to be marked compatible at AMO for it to work in Thunderbird 60.  I have tested TB60 with strict compaibility FALSE and quotecollapse works, so marking compatible might be the only change needed.  If not, then please consult https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57

BTW, I love QC!

**Comment by mjg** [comment]
Thanks for the feedback, both technical and empathetical :)

I've marked the addon for TB60 on AMO now.
