### ISSUE TITLE
Signature is placed over quoted text when replying

### ISSUE THREAD

**Issue by TheBoardMan** [mjg/QuoteCollapse#7]
I reported a bug with bugzilla ([#1465084](https://bugzilla.mozilla.org/show_bug.cgi?id=1465084)), but it turned out that QuoteCollapse was the cause.

**Comment by mjg** [comment]
Thanks for the report. Is this something that used to work with QuoteCollapse and stopped working after a QuoteCollapse update, or are you a new QuoteCollapse user?

**Comment by TheBoardMan** [comment]
I've been using QuoteCollapse for many years (10 or 15?) without problems. Recently, I started realising this effect. I think since about one or two monthsago. (Last update seems to have been 4-4-2018, so it could be the update.) Is it possible to go back one version to see if that solves the problem?

**Comment by TheBoardMan** [comment]
I went back to version 0.9 and can confirm that that version still shows the signature in the correct place.

**Comment by stanio** [comment]
@TheBoardMan, could you take a look at #2 and note the [backward-compatibility remark](/mjg/QuoteCollapse/issues/2#issuecomment-382641374) – does addressing it fixes the issue for you?

**Comment by TheBoardMan** [comment]
Yes. In my userChrome I had turned off QuoteCollapse for the 1st level and re-enabled it for the other levels (some snippet I had found somewhere). I removed it and how everything works again (except that the first level is collapsed by default).
Thanks.

**Comment by stanio** [comment]
Note, you don't need to completely remove your preferred customization – just adjust it as written:

> ... `height: auto` → `max-height: none`, and replace other `height` usages for `max-height`.

**Comment by TheBoardMan** [comment]
You are right again. If forgot the `auto` → `none` part. Problem solved.
