### ISSUE TITLE
quotecollapse becomes very slow

### ISSUE THREAD

**Issue by milgit** [mjg/QuoteCollapse#9]
In a long mail thread where users kept replying while adding to, and including the previous messages, quotecollpse takes minutes to handle the newest messages in the thread.  Thunderbird is unresponsive for maybe 10 minutes at a time.

**Comment by stanio** [comment]
bf2f21f3d67d84f30fbbf6983ce1becdf8f24858 (part of #8) may resolve this.  I've noticed similar behavior previously and this change appears to fix it for me.  I could prepare a fix with just this change, and I will post a test build for anyone to try.

**Comment by milgit** [comment]
The new version is much faster for the email thread that I previously had problems with.  It collapses only one level of message, and not at all when there are many levels of quoted messages.  It may be that most of the replies are 1 line.

This is less than ideal, but is more usable than the old behavior of causing Thunderbird to hang for 10 minutes at a time.

**Comment by stanio** [comment]
> It collapses only one level of message, and not at all when there are many levels of quoted messages... This is less than ideal...

Could you elaborate a bit further?  I'm having trouble imagining what's the actual case – couple of screenshots showing actual, and possibly expected state, would help.  If content is really private, could you edit the images to mask the text?

**Comment by milgit** [comment]
I tried reproducing the issue with a long thread not collapsing, but I can't reproduce it - except with the original email thread that I had reported the problems with.  For all other email threads, quotecollapse is working for me.  I can live with that.

If I run into another symptom, I will report that symptom in a new bug.

**Comment by mjg** [comment]
#10 is merged now. Thanks @milgit and @stanio !
